### ISSUE TITLE
Test network crashing with congested transit assignment

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-model-system#115]
This is probably just me but I am writing this here as a reminder!

Helmet run crashes when using the small test network. It is not compatible with congested transit assignment. Here is the error log:

```
2020-01-09 12:15:02,338 [INFO] Starting iteration 5
2020-01-09 12:15:02,351 [DEBUG] Added demand for freight, truck
2020-01-09 12:15:02,352 [DEBUG] Added demand for freight, trailer_truck
2020-01-09 12:15:04,053 [DEBUG] Added demand for hw, car
2020-01-09 12:15:04,055 [DEBUG] Added demand for hw, transit
2020-01-09 12:15:04,055 [DEBUG] Added demand for hw, bike
2020-01-09 12:15:04,391 [DEBUG] Added demand for hc, car
...
2020-01-09 12:15:07,664 [DEBUG] Added demand for oop, transit
2020-01-09 12:15:07,678 [WARNING] 1x1 matrix not matching 28 demand shares.Resorted to backup demand shares.
2020-01-09 12:15:07,678 [WARNING] 1x1 matrix not matching 28 demand shares.Resorted to backup demand shares.
2020-01-09 12:15:07,678 [DEBUG] Added demand for external, car
2020-01-09 12:15:07,710 [DEBUG] Added demand for external, transit
2020-01-09 12:15:07,717 [DEBUG] Added demand for external, truck
2020-01-09 12:15:07,733 [DEBUG] Added demand for external, trailer_truck
2020-01-09 12:15:07,733 [INFO] Assignment starts...
2020-01-09 12:15:07,963 [INFO] Car assignment started...
2020-01-09 12:15:08,394 [INFO] Car assignment performed for scenario 23
2020-01-09 12:15:08,723 [INFO] Calculates cumulative travel times for scenario 23
2020-01-09 12:15:09,549 [INFO] Congested transit assignment started
2020-01-09 12:15:10,963 [ERROR] Exception at iteration 5
Traceback (most recent call last):
  File "C:\Users\xxx\Home\helmet\helmet-model-system\Scripts\helmet_app.py", line 60, in run
    impedance = self.model.run(impedance, is_last_iteration=True)
  File "C:\Users\xxx\Home\helmet\helmet-model-system\Scripts\modelsystem.py", line 150, in run
    self.ass_model.assign(tp, self.dtm.demand[tp], is_last_iteration)
  File "C:\Users\xxx\Home\helmet\helmet-model-system\Scripts\assignment\emme_assignment.py", line 56, in assign
    self._assign_congested_transit(scen_id)
  File "C:\Users\xxx\Home\helmet\helmet-model-system\Scripts\assignment\emme_assignment.py", line 772, in _assign_congested_transit
    log_worksheets=False, scenario=scenario)
  File "standard\inro\emme\transit_assignment\congested_transit_assignment.py", line 583, in __call__
  File "standard\inro\emme\transit_assignment\congested_transit_assignment.py", line 636, in run_congested_transit_assignment
  File "inro\director\logging\trail.py", line 271, in __trace
  File "standard\inro\emme\transit_assignment\congested_transit_assignment.py", line 1337, in line_search
ArgumentError: Congested transit assignment cannot be applied to this transit network, please use Capacitated transit assignment instead.
2020-01-09 12:15:10,973 [ERROR] Fatal error occured, simulation aborted.
2020-01-09 12:15:10,973 [INFO] Simulation ended.
```

There is also something saying `[WARNING] 1x1 matrix not matching 28 demand shares.Resorted to backup demand shares` there.

**Comment by johpiip** [comment]
The results still appear in the `Results` folder... Maybe the last errors should be changed to warnings if the model system can make the change from congested transit assignment to capacitated transit assignment automatically. Like, "warning" -> simulation still goes through, "error" -> simulation did not go through and this error message tells you why.

**Comment by zptro** [comment]
Need to develop a better test network.
