### ISSUE TITLE
Running base scenario with mock assignment fails: missing "transit_uncongested" matrix

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-model-system#281]
- Lähtödata: zonedata 2020-09-08, base matrices 2020-09-08--2021-01-11
- Syöttötiedot: zonedata same as above, matrices from `helmet_4.0.4_2018_results`
- In `dev-config.json`, `"USE_EMME": false`

I receive the following error log. Time matrices in 2018 do not include `transit_uncongested` but time matrices in test scenario do.

```
[UI-event] Initializing run of scenarios: v2018
[INFO 10:19] Checking base inputdata...
[INFO 10:19] Reading matrices from C:\Users\PiippJo\Home\malliajot\03_Tulokset\v2018\Matrices
[INFO 10:20] Checking base zonedata & scenario-based input data...
[INFO 10:20] Checking input data for scenario #0 ...
[INFO 10:20] Successfully validated all input files
[UI-event] Running scenario "v2018"
[DEBUG] sys.version_info=2
[DEBUG] sys.path=['C:\\Users\\PiippJo\\Home\\malliajot\\helmet-model-system-v4.0.3-30-02-1617105350359', 'C:\\WINDOWS\\SYSTEM32\\python27.zip', 'c:\\python27\\DLLs', 'c:\\python27\\lib', 'c:\\python27\\lib\\plat-win', 'c:\\python27\\lib\\lib-tk', 'C:\\Users\\PiippJo\\.virtualenvs\\Scripts-AJXyDTuP\\Scripts', 'C:\\Users\\PiippJo\\.virtualenvs\\Scripts-AJXyDTuP', 'C:\\Users\\PiippJo\\.virtualenvs\\Scripts-AJXyDTuP\\lib\\site-packages']
[DEBUG] log_level=DEBUG
[DEBUG] emme_path=C:\Users\PiippJo\Home\malliajot\02_Syottotiedot\v2018.emp
[DEBUG] baseline_data_path=C:\Users\PiippJo\Home\malliajot\01_Lahtodata\lahtodata_2018
[DEBUG] forecast_data_path=C:\Users\PiippJo\Home\malliajot\02_Syottotiedot\syottotiedot_v2018
[DEBUG] iterations=3
[DEBUG] use_fixed_transit_cost=False
[DEBUG] save_matrices=True
[DEBUG] del_strat_files=True
[DEBUG] first_scenario_id=19
[DEBUG] scenario_name=v2018
[INFO 10:20] Initializing matrices and models..
[INFO 10:20] Initializing MockAssignmentModel..
[INFO 10:20] Reading matrices from C:\Users\PiippJo\Home\malliajot\03_Tulokset\v2018\Matrices
[INFO 10:20] Starting simulation with 3 iterations..
[INFO 10:20] Calculating transit cost
[INFO 10:20] Using aggregated transit cost data transit_cost_peripheral.txt
[INFO 10:20] Assigning period iht
[INFO 10:20] Saved demand matrices for iht
[ERROR] {"args":["--log-level","DEBUG","--log-format","JSON","--scenario-name","v2018","--results-path","C:\\Users\\PiippJo\\Home\\malliajot\\03_Tulokset","--emme-path","C:\\Users\\PiippJo\\Home\\malliajot\\02_Syottotiedot\\v2018.emp","--first-scenario-id",19,"--baseline-data-path","C:\\Users\\PiippJo\\Home\\malliajot\\01_Lahtodata\\lahtodata_2018","--forecast-data-path","C:\\Users\\PiippJo\\Home\\malliajot\\02_Syottotiedot\\syottotiedot_v2018","--iterations","3"],"executable":"C:\\Users\\PiippJo\\.virtualenvs\\Scripts-AJXyDTuP\\Scripts\\python.exe","exitCode":1,"options":["-u"],"script":"C:\\Users\\PiippJo\\Home\\malliajot\\helmet-model-system-v4.0.3-30-02-1617105350359\\helmet.py"}
[ERROR] {"message": "sys.version_info=2", "level": "DEBUG"}
{"message": "sys.path=['C:\\\\Users\\\\PiippJo\\\\Home\\\\malliajot\\\\helmet-model-system-v4.0.3-30-02-1617105350359', 'C:\\\\WINDOWS\\\\SYSTEM32\\\\python27.zip', 'c:\\\\python27\\\\DLLs', 'c:\\\\python27\\\\lib', 'c:\\\\python27\\\\lib\\\\plat-win', 'c:\\\\python27\\\\lib\\\\lib-tk', 'C:\\\\Users\\\\PiippJo\\\\.virtualenvs\\\\Scripts-AJXyDTuP\\\\Scripts', 'C:\\\\Users\\\\PiippJo\\\\.virtualenvs\\\\Scripts-AJXyDTuP', 'C:\\\\Users\\\\PiippJo\\\\.virtualenvs\\\\Scripts-AJXyDTuP\\\\lib\\\\site-packages']", "level": "DEBUG"}
{"message": "log_level=DEBUG", "level": "DEBUG"}
{"message": "emme_path=C:\\Users\\PiippJo\\Home\\malliajot\\02_Syottotiedot\\v2018.emp", "level": "DEBUG"}
{"message": "baseline_data_path=C:\\Users\\PiippJo\\Home\\malliajot\\01_Lahtodata\\lahtodata_2018", "level": "DEBUG"}
{"message": "forecast_data_path=C:\\Users\\PiippJo\\Home\\malliajot\\02_Syottotiedot\\syottotiedot_v2018", "level": "DEBUG"}
{"message": "iterations=3", "level": "DEBUG"}
{"message": "use_fixed_transit_cost=False", "level": "DEBUG"}
{"message": "save_matrices=True", "level": "DEBUG"}
{"message": "del_strat_files=True", "level": "DEBUG"}
{"message": "first_scenario_id=19", "level": "DEBUG"}
{"message": "scenario_name=v2018", "level": "DEBUG"}
{"status": {"name": "v2018", "completed": 0, "current": 0, "failed": 0, "state": "starting", "total": 3, "log": "C:\\Users\\PiippJo\\Home\\malliajot\\helmet-model-system-v4.0.3-30-02-1617105350359\\v2018.log"}, "message": "Initializing matrices and models..", "level": "INFO"}
{"message": "Initializing MockAssignmentModel..", "level": "INFO"}
{"message": "Reading matrices from C:\\Users\\PiippJo\\Home\\malliajot\\03_Tulokset\\v2018\\Matrices", "level": "INFO"}
{"status": {"name": "v2018", "completed": 0, "results": [], "current": 0, "failed": 0, "state": "preparing", "total": 3, "log": "C:\\Users\\PiippJo\\Home\\malliajot\\helmet-model-system-v4.0.3-30-02-1617105350359\\v2018.log"}, "message": "Starting simulation with 3 iterations..", "level": "INFO"}
{"message": "Calculating transit cost", "level": "INFO"}
{"message": "Using aggregated transit cost data transit_cost_peripheral.txt", "level": "INFO"}
{"message": "Assigning period iht", "level": "INFO"}
{"message": "Saved demand matrices for iht", "level": "INFO"}
Traceback (most recent call last):
  File "C:\Users\PiippJo\Home\malliajot\helmet-model-system-v4.0.3-30-02-1617105350359\helmet.py", line 217, in <module>
    main(args)
  File "C:\Users\PiippJo\Home\malliajot\helmet-model-system-v4.0.3-30-02-1617105350359\helmet.py", line 70, in main
    impedance = model.assign_base_demand(args.use_fixed_transit_cost, iterations==0)
  File "C:\Users\PiippJo\Home\malliajot\helmet-model-system-v4.0.3-30-02-1617105350359\modelsystem.py", line 189, in assign_base_demand
    iteration=("last" if is_end_assignment else 0))
  File "C:\Users\PiippJo\Home\malliajot\helmet-model-system-v4.0.3-30-02-1617105350359\assignment\mock_assignment.py", line 82, in assign
    matrices["time"]["transit_work"] = matrices["time"]["transit_uncongested"]
KeyError: 'transit_uncongested'
[UI-event] Scenario "v2018" finished
```

**Comment by johpiip** [comment]
Hey @zptro, when you have time, could you help me with this? My question is whether this is an error in my input data or a bug in the model system. 😄 If you can point me to the right direction, you can assign this issue to me.

**Comment by zptro** [comment]
The reason seems to be that I have run an end-assignment-only (iterations=0) model run (I don't remember exactly why, but probably because I just needed to re-run result prints from the assignment, not the whole demand calculation). And the uncongested transit time is saved from the second-to-last iteration.

**Comment by johpiip** [comment]
Ah, okay! I will close this issue since the issue is in the matrices and not in helmet-model-system. :) Thanks!
