### ISSUE TITLE
Raise an error when link mode has only `h`

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-model-system#456]
Right now, this is what happens:

```
...
[INFO 09:15] Pedestrian assignment started...
[INFO 09:15] Pedestrian assignment performed for scenario 51
[INFO 09:15] Sets bike functions for scenario 51
[EXCEPTION] Traceback (most recent call last):
[EXCEPTION]   File "C:\helmet\helmet_41\model-systems\helmet-model-system\Scripts\helmet.py", line 261, in <module>
[EXCEPTION]     main(args)
[EXCEPTION]   File "C:\helmet\helmet_41\model-systems\helmet-model-system\Scripts\helmet.py", line 95, in main
[EXCEPTION]     args.use_fixed_transit_cost, iterations==0)
[EXCEPTION]   File "C:\helmet\helmet_41\model-systems\helmet-model-system\Scripts\modelsystem.py", line 175, in assign_base_demand
[EXCEPTION]     self.ass_model.init_assign(base_demand)
[EXCEPTION]   File "C:\helmet\helmet_41\model-systems\helmet-model-system\Scripts\assignment\emme_assignment.py", line 109, in init_assign
[EXCEPTION]     ap0.assign(demand, iteration="init")
[EXCEPTION]   File "C:\helmet\helmet_41\model-systems\helmet-model-system\Scripts\assignment\assignment_period.py", line 93, in assign
[EXCEPTION]     self._set_bike_vdfs()
[EXCEPTION]   File "C:\helmet\helmet_41\model-systems\helmet-model-system\Scripts\assignment\assignment_period.py", line 364, in _set_bike_vdfs
[EXCEPTION]     link.modes -= {main_mode}
[EXCEPTION]   File "inro\emme\network\link.py", line 170, in modes
[EXCEPTION]   File "inro\emme\network\__init__.py", line 149, in _validate_modes
[EXCEPTION] inro.emme.core.exception.Error: Link must allow at least one mode
```

We could have error handling either there on line 364, or during network validation.

**Comment by hsl-petrhaj** [comment]
At the same time "1" links should be checked.

**Comment by johpiip** [comment]
> At the same time "1" links should be checked.

I made a new issue of this.
